[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.3"

[prune]
go-tests = true
unused-packages = true
non-go = true
